## Adjust this file to your liking. 
## This file is used for both the preprocessing and the Rshiny app
## This allows for Python and R to know file locations and settings
## Do not alter the preprocessing script unless adaptations are necessary

# Folder for data files:
folder: "/home/pascal/Data/"

# RShiny folder
shiny_folder: /home/pascal/ShinyApps/atlas

# Parse Options

# Gene Ontology identifier to use for filter (GO:0045087 = Innate Immune response)
GO_ID: GO:0045087 

# Confidence threshold for StringDB protein-protein interactions 
# 700 for high confidence, 400 for medium, 0 for all interactions
confidence: 700 

# Keep metabolites in the dataset without connections to the filter?
keep_metabolites: True 

# Keep proteins in the dataset without connections to the filter?
keep_proteins: True


### Input database files:
## See thesis for links to these files

# Uniprot: Filename containing XML of all human proteins
uniprot: Uniprot-homosapiens

# Tab-delimited file for StringDB
stringdb: 9606.protein.links.v11.0.txt

# XML file for HMDB
hmdb: hmdb_metabolites.xml

### Output files:

# Gene Ontology files
# Direct = No neighbours, just filter
# Indirect_1 = Include first neighbour of Direct set
# Indirect_2 = Include first & second neighbour of Direct set
g_direct: go-process_direct.tsv
g_indirect_1: go-process_indirect_1.tsv
g_indirect_2: go-process_indirect_2.tsv

# Filename of Gene Ontology cellular locations
GO-cellular: go-cellular.tsv

# File names for protein-protein interactions
p_direct: p_direct.tsv
p_indirect_1: p_indirect_1.tsv
p_indirect_2: p_indirect_2.tsv

# File names for metabolite-protein interactions
m_direct: m_direct.tsv
m_indirect_1: m_indirect_1.tsv
m_indirect_2: m_indirect_2.tsv

# File names for metabolite-metabolite interactions
metabolite_metabolite: metabolite_metabolite
metabolite_metabolite1: metabolite_metabolite1
metabolite_metabolite2: metabolite_metabolite2

# Synonyms for proteins
synonyms: synonyms.tsv

# Alternate HMDB identifiers for backwards compatibility
alternative_hmdbs: alternate_metabolites.tsv

# Metabolite info, which should be parsed?
# Defaults to: Proteins, Diseases, Pathways, Tissues, Cellular & Biospecimen
Metabolite Info:
- Proteins
- Diseases
- Pathways
- Tissues
- Cellular
- Biospecimen

# Metabolite prefix: Which prefix should be used for the Metabolite Info files?
# Default: HMDB_
metabolite_prefix: HMDB_
