---
title: "Controls"
output: html_document

---

### __Network__
The network is a semi-static image that allows for some mouse controls. Clicking on a metabolite or protein will result in a popup containing information about the node. This schematic overview shows the current interactions of the node and includes secondary information.

Using the scroll wheel allows for zooming into the current hovering region. There are no limits on the zoom distance. When no nodes are visible, it is advised to rebuild te network by clicking the 'Build' button.

Double-clicking on the network starts the shortest-path mode. This allows you to find the shortest path to another node in the network. By double-clicking on the second node of interest, a subnetwork between these nodes will show. Returning to the original network can be done by rebuilding the network by clicking the 'Build' button.



------

### __Heatmap__
After plotting the data selected using the 'Build' button, the heatmap tab will show a heatmap. This heatmap will display both the "upper" and "lower" matrix of the interactions in the data. 

The values in the heatmap display the distances between metabolites and proteins with 1 being an direct interaction and 0 being no interaction path found. The legend on the right will display the colors representive of those values.

By hovering the mouse over one of the cells of the heatmap, the name of both metabolites / proteins is displayed including their value. 

------

### __Statistics__

The Statistics tab contains two boxes each containing a plot of either raw counts or p-values indicating the significance of the Gene Ontologuy term. The raw counts are shown using a piechart, while p-values are indicated by a barplot. Hovering over the barplot will indicate the p-value of the current term. Note: Not all Gene Ontology terms are given, only the ones that fall in the scope of the Gene Ontology term given at preprocessing.

------

### __Data table__
The Data Table tab shows all interactions between proteins and/or metabolites currently plotted. 

------

### __Importing data__
This app supports bulk import of metabolite data using files. In the left menu click on 'File Import'. 
